# Generated by Django 4.0.3 on 2022-05-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='house_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
