# Generated by Django 4.0.3 on 2022-05-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_houses_house_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
